### ISSUE TITLE
Releasing 1.1

### ISSUE THREAD

**Issue by szepeviktor** [benhuson/wp-mailfrom#12]
@benhuson Are you planning to release 1.1 on WP-org?
I would gladly do that if you add me (`szepe.viktor`) as a contributor on WP.org.

**Comment by benhuson** [comment]
I will be doing soon - just want to test a couple more things.

Have you tested the current master branch here on GitHub? Is it all working OK for you?
https://github.com/benhuson/wp-mailfrom

**Comment by szepeviktor** [comment]
Yes, of course.

**Comment by szepeviktor** [comment]
It would be very nice to solve all open issues too.

**Comment by benhuson** [comment]
If we can get #8 sorted, lets release 1.1, then tackle any other issues.

**Comment by benhuson** [comment]
Happy for you to contribute pull requests :smile:

**Comment by szepeviktor** [comment]
Released.
