### ISSUE TITLE
Deprecated screen_icon

### ISSUE THREAD

**Issue by szepeviktor** [benhuson/wp-mailfrom#17]
@benhuson Would it be possible to create a new release?

https://github.com/benhuson/wp-mailfrom/blob/84127131df492d751eb9deedd5cd9ca616f3948e/admin/views/admin.php#L15

**Comment by benhuson** [comment]
Fixed in https://github.com/benhuson/wp-mailfrom/commit/a0b236bece1541b972e716639ee5d7072ff78110

**Comment by szepeviktor** [comment]
Thank you.
